Mediaverify - fix Verify buttons [Extra files] tab error
Select Verify button in the resulting Extra Files tab double click on any file name (TypeError: open_file_with_default_application() missing 1 required positional argument: uistate)